package core.project.messaging.domain.articles.enumerations;

public enum ArticleTag {
    OPENINGS,
    MIDDLEGAME,
    ENDGAME,
    TACTICS,
    STRATEGY,
    ATTACK,
    DEFENSE,
    BEGINNER,
    INTERMEDIATE,
    ADVANCED,
    GRANDMASTER,
    GAME_ANALYSIS,
    THEORY,
    CLASSIC_GAMES,
    HISTORY,
    LEGENDS,
    CHESS_BOOKS,
    TOURNAMENTS,
    WORLD_CHAMPIONSHIP,
    ONLINE_CHESS,
    PUZZLES,
    TRAINING,
    BLITZ,
    BULLET,
    CLASSICAL,
    CHESS_ENGINES,
    AI,
    ENDGAME_TABLEBASES,
    FUN,
    CHESS_AND_LIFE
}